### ISSUE TITLE
CBRN

### ISSUE THREAD

**Issue by Zycorge** [fire-391/3dMP#2]
Approved by CS

US-SOC CBT Suite(multi)    (Multicam CBRN Combat Uniform)

Classname: U_mas_usl_B_suite_VEG
 

US-SOC CBT Suite(black)    (Black CBRN Combat Uniform)

Classname: U_mas_usl_B_suite_CQB

US-SOC NBC Mask     (Gas Mask)
﻿ Classname: G_mas_usl_gasmask

**Comment by fire-391** [comment]
Added with commit f115d33. When would you like this released?

**Comment by Zycorge** [comment]
> Added with commit [f115d33](https://github.com/fire-391/3dMP/commit/f115d33c35a2f4bc4d957236e5d0070d2ee3397e). When would you like this released?

Whenever you'd like. Thursday during the briefing is when we will be running the unit through it all so I'd say anytime by Thursday
